name: ticker_text
description: Configurable & straightforward text scroller with minimal dependencies.
version: 2.1.0
homepage: https://github.com/arafatamim/ticker_text

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  fading_edge_scrollview: ^4.1.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
